src/CadastroEscolar.Presentation.MVC/Models/ErrorViewModel.cs
namespace CadastroEscolar.Presentation.MVC.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

src/CadastroEscolar.Presentation.MVC/Controllers/AlunosController.cs
using CadastroEscolar.Domain.Services.Interfaces;
using CadastroEscolar.Domain.Services.Requests;
using CadastroEscolar.Domain.Services.Responses;
using Microsoft.AspNetCore.Mvc;

namespace CadastroEscolar.Presentation.MVC.Controllers;

public class AlunosController : Controller
{
    private readonly IAlunoService _alunoService;
    private readonly IProfessorService _professorService; 

    public AlunosController(IAlunoService alunoService, IProfessorService professorService)
    {
        _alunoService = alunoService;
        _professorService = professorService; 
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        IEnumerable<AlunoResponse> alunos = await _alunoService.ListarAlunos();

        ViewBag.Professores =
            await _professorService.ListarProfessores();

        return View(alunos);
    }

    [HttpPost]
    public async Task<IActionResult> CadastrarAluno(AdicionarAlunoRequest request)
    {
        await _alunoService.CadastrarAluno(request);

        IEnumerable<AlunoResponse> alunos = await _alunoService.ListarAlunos();

        TempData["Mensagem"] = "Aluno adicionado com sucesso!";

        return RedirectToAction("Index", alunos);
    }

    [HttpGet("alunos-professor")]
    public async Task<IActionResult> BuscarAlunosProfessor(Guid professorId, bool mostrarBotaoLote = true)
    {
        var alunos = await _alunoService.ListarAlunosPorProfessor(professorId);

        ViewBag.Professores =
            await _professorService.ListarProfessores();

        ViewBag.MostrarBotaoLote = mostrarBotaoLote;
        ViewBag.ProfessorId = professorId;

        return View("Index", alunos);
    }


    [HttpPost]
    public async Task<IActionResult> ExcluirAluno(Guid alunoId)
    {
        await _alunoService.ExcluirAluno(alunoId);

        return RedirectToAction("Index");
    }

    [HttpPost]
    public async Task<IActionResult> CadastrarAlunosEmLote(IFormFile file, Guid professorId)
    {
        var response = await _alunoService.IncluirAlunosEmLote(file, professorId);

        if (response.Success)
        {
            TempData["Mensagem"] = response.Message;
        }
        else
        {
            TempData["Erro"] = response.Message;
        }

        return RedirectToAction("Index");
    }
}

src/CadastroEscolar.Presentation.MVC/Controllers/HomeController.cs
using System.Diagnostics;
using CadastroEscolar.Domain.Services.Interfaces;
using CadastroEscolar.Domain.Services.Requests;
using Microsoft.AspNetCore.Mvc;
using CadastroEscolar.Presentation.MVC.Models;

namespace CadastroEscolar.Presentation.MVC.Controllers;

public class HomeController : Controller
{
    private readonly IProfessorService _professorService;

    public HomeController(IProfessorService professorService)
    {
        _professorService = professorService;
    }

    [HttpGet]
    public async Task<IActionResult> Index()
    {
        var professores = await _professorService.ListarProfessores();
        return View(professores);
    }

    [HttpPost]
    public async Task<IActionResult> CadastrarProfessor(string nome)
    {
        var professorRequest = new AdicionarProfessorRequest
        {
            Nome = nome
        };

        await _professorService.AdicionarProfessor(professorRequest);

        var professores = await _professorService.ListarProfessores();

        TempData["Mensagem"] = "Professor adicionado com sucesso!";

        return View("Index", professores);
    }

}

src/CadastroEscolar.Presentation.MVC/Views/Alunos/Index.cshtml
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<table class="table table-striped">
    
    @if (ViewBag.MostrarBotaoLote == true)
    { 
        <form id="myForm" enctype="multipart/form-data" action="@Url.Action("CadastrarAlunosEmLote", "Alunos")" method="post" style="display: none;">
            <input type="hidden" name="professorId" value="@ViewBag.ProfessorId"/>
            <div class="form-group custom-file-input">
                <input type="file" id="file" name="file" required class="real-file" style="display: none;"/>
                <label for="file" class="custom-file-label">Escolha um arquivo</label>
            </div> 
        </form>
 
        <button id="triggerFileInput" class="btn btn-primary">Cadastrar Alunos em Lote</button>
    }
    else
    {
        <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#cadastrarAlunoModal">Cadastrar Aluno</button>
    }
    
    <thead>
    <tr>
        <th scope="col">Nome</th>
        <th scope="col">Mensalidade</th>
        <th scope="col">Data de Vencimento</th>
        <th scope="col">Nome do Professor</th>
        <th scope="col">Ação</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var aluno in Model)
    {
        <tr>
            <td>@aluno.Nome</td>
            <td>@aluno.Mensalidade.ToString("C")</td>
            <td>@aluno.DataVencimento.ToShortDateString()</td>
            <td>@aluno.NomeProfessor</td>
            <td>
                <form method="post" action="@Url.Action("ExcluirAluno", "Alunos", new { alunoId = aluno.Id })">
                    <button type="submit" class="btn btn-danger">Excluir</button>
                </form>
            </td>
        </tr>
    }
    </tbody>
</table>

<div class="modal fade" id="cadastrarAlunoModal" tabindex="-1" aria-labelledby="cadastrarAlunoModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="cadastrarAlunoModalLabel">Cadastrar Novo Aluno</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="formCadastrarAluno" method="post" action="@Url.Action("CadastrarAluno", "Alunos")">
                    <div class="mb-3">
                        <label for="nomeAluno" class="form-label">Nome</label>
                        <input type="text" class="form-control" id="nomeAluno" name="nome" required>
                    </div>
                    <div class="mb-3">
                        <label for="mensalidadeAluno" class="form-label">Mensalidade</label>
                        <input type="number" step="0.01" class="form-control" id="mensalidadeAluno" name="mensalidade" required>
                    </div>
                    <div class="mb-3">
                        <label for="dataVencimentoAluno" class="form-label">Data de Vencimento</label>
                        <input type="date" class="form-control" id="dataVencimentoAluno" name="dataVencimento" required>
                    </div>
                    <div class="mb-3">
                        <label for="professorAluno" class="form-label">Professor</label>
                        <select class="form-control" id="professorAluno" name="professorId" required>
                            @foreach (var professor in ViewBag.Professores)
                            {
                                <option value="@professor.Id">@professor.Nome</option>
                            }
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary">Adicionar</button>
                </form>
            </div>
        </div>
    </div>
</div>

@if (TempData["Mensagem"] != null)
{
    <div class="alert alert-success">
        @TempData["Mensagem"]
    </div>
}

@if (TempData["Erro"] != null)
{
    <div class="alert alert-danger">
        @TempData["Erro"]
    </div>
}


<script>
$(document).ready(function() {
    $('#triggerFileInput').click(function() {
        $('#file').click();
    });

    $('#file').change(function() {
        if ($(this).val() !== '') {
            $('#myForm').submit();
        }
    });
});
</script>

src/CadastroEscolar.Presentation.MVC/Views/Home/Index.cshtml
@using CadastroEscolar.Domain.Entities
<table class="table table-striped">
    <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#cadastrarProfessorModal">Cadastrar Professor</button>
    <thead>
    <tr>
        <th scope="col">ID</th>
        <th scope="col">Nome</th>
        <th scope="col">Ação</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var professor in Model)
    {
        <tr>
            <td>@professor.Id</td>
            <td>@professor.Nome</td>
            <td>
                <button class="btn btn-primary" onclick="location.href='@Url.Action("BuscarAlunosProfessor", "Alunos", new { professorId = professor.Id })'">Mostrar Alunos</button>
            </td>
        </tr>
    }
    </tbody>
</table>

<div class="modal fade" id="cadastrarProfessorModal" tabindex="-1" aria-labelledby="cadastrarProfessorModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="cadastrarProfessorModalLabel">Cadastrar Novo Professor</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="formCadastrarProfessor" method="post" action="@Url.Action("CadastrarProfessor", "Home")">
                    <div class="mb-3">
                        <label for="nomeProfessor" class="form-label">Nome</label>
                        <input type="text" class="form-control" id="nomeProfessor" name="nome" required>
                    </div>
                    <button type="submit" class="btn btn-primary">Adicionar</button>
                </form>
            </div>
        </div>
    </div>
</div>

@if (TempData["Mensagem"] != null)
{
    <div class="alert alert-success">
        @TempData["Mensagem"]
    </div>
}

src/CadastroEscolar.Presentation.MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - CadastroEscolar.Presentation.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/CadastroEscolar.Presentation.MVC.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Cadastro Escolar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Alunos" asp-action="Index">Alunos</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>